package co.greensqa.testdata.repository;

import co.greensqa.testdata.domain.*;
import org.h2.jdbcx.JdbcDataSource;

import java.sql.*;
import java.util.*;

public final class H2PersonRepository implements PersonRepository {
    private final JdbcDataSource dataSource = new JdbcDataSource();

    public H2PersonRepository(String jdbcUrl) {
        dataSource.setURL(jdbcUrl);
        dataSource.setUser("sa");
        initialize();
    }

    private void initialize() {
        String ddl = """
            CREATE TABLE IF NOT EXISTS test_person (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              person_type VARCHAR(12) NOT NULL,
              name VARCHAR(100) NOT NULL,
              last_name VARCHAR(100) NOT NULL,
              age INT NOT NULL CHECK (age > 10 AND age < 80),
              document VARCHAR(20) NOT NULL UNIQUE,
              city VARCHAR(80) NOT NULL,
              country VARCHAR(80) NOT NULL,
              language VARCHAR(40) NOT NULL,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
              CONSTRAINT uq_person_name UNIQUE(name, last_name)
            )
            """;
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute(ddl);
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot initialize database", e);
        }
    }

    @Override public TestPerson save(TestPerson person) {
        String sql = "INSERT INTO test_person(person_type,name,last_name,age,document,city,country,language) VALUES(?,?,?,?,?,?,?,?)";
        try (Connection c = dataSource.getConnection();
             PreparedStatement ps = c.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, person.type().name());
            ps.setString(2, person.name());
            ps.setString(3, person.lastName());
            ps.setInt(4, person.age());
            ps.setString(5, person.document());
            ps.setString(6, person.city());
            ps.setString(7, person.country());
            ps.setString(8, person.language());
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys.next()) person.assignId(keys.getLong(1));
            }
            return person;
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot save person", e);
        }
    }

    @Override public List<TestPerson> findAll() {
        List<TestPerson> result = new ArrayList<>();
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement();
             ResultSet rs = s.executeQuery("SELECT * FROM test_person ORDER BY id")) {
            while (rs.next()) result.add(map(rs));
            return result;
        } catch (SQLException e) { throw new IllegalStateException("Cannot list people", e); }
    }

    @Override public Optional<TestPerson> findById(long id) {
        try (Connection c = dataSource.getConnection(); PreparedStatement ps = c.prepareStatement("SELECT * FROM test_person WHERE id=?")) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) { return rs.next() ? Optional.of(map(rs)) : Optional.empty(); }
        } catch (SQLException e) { throw new IllegalStateException("Cannot find person", e); }
    }

    @Override public boolean deleteById(long id) {
        try (Connection c = dataSource.getConnection(); PreparedStatement ps = c.prepareStatement("DELETE FROM test_person WHERE id=?")) {
            ps.setLong(1, id); return ps.executeUpdate() == 1;
        } catch (SQLException e) { throw new IllegalStateException("Cannot delete person", e); }
    }

    @Override public int deleteAll() {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            return s.executeUpdate("DELETE FROM test_person");
        } catch (SQLException e) { throw new IllegalStateException("Cannot clear people", e); }
    }

    @Override public Set<String> existingDocuments() { return stringSet("SELECT document FROM test_person", false); }
    @Override public Set<String> existingFullNames() { return stringSet("SELECT name,last_name FROM test_person", true); }

    private Set<String> stringSet(String sql, boolean fullName) {
        Set<String> values = new HashSet<>();
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement(); ResultSet rs = s.executeQuery(sql)) {
            while (rs.next()) values.add(fullName ? key(rs.getString(1), rs.getString(2)) : rs.getString(1));
            return values;
        } catch (SQLException e) { throw new IllegalStateException("Cannot read uniqueness data", e); }
    }

    public static String key(String name, String lastName) { return name + "\u0000" + lastName; }

    private TestPerson map(ResultSet rs) throws SQLException {
        PersonType type = PersonType.valueOf(rs.getString("person_type"));
        if (type == PersonType.COMPANY) {
            return new Company(rs.getLong("id"), rs.getString("name"), rs.getInt("age"), rs.getString("document"),
                    rs.getString("city"), rs.getString("country"), rs.getString("language"));
        }
        return new Individual(rs.getLong("id"), rs.getString("name"), rs.getString("last_name"), rs.getInt("age"),
                rs.getString("document"), rs.getString("city"), rs.getString("country"), rs.getString("language"));
    }
}
